<img src="idal-logo.png" align="right" style="float" width="400">
<font color="#CA3532"><h1 align="left">Master en Ciencia de Datos</h1></font>
<font color="#6E6E6E"><h2 align="left">Tarea Extra 3. </h2></font> 
<font color="#6E6E6E"><h2 align="left">28-09-2021 </h2></font> 

#### Jorge Vila Tomás

# Definición

En matemáticas, la pseudoinversa $A^+$ de una matriz $A$ es una generalización de la matriz inversa.

* Un uso común de la pseudoinversa es el de encontrar una solución de «ajuste óptimo» (por mínimos cuadrados) de un sistema de ecuaciones lineales que no posee solución única. 
* Otro uso es hallar la solución de norma mínima (euclídea) de un sistema de ecuaciones lineales con múltiples soluciones. 

La pseudoinversa $A^+=VS^{-1}U^t$ se obtiene a través de la descomposición en valores singulares (SVD) de la matriz $A=USV^t$. 

# Descomposición en valores singulares 

Crea una array $A$ definido omo una matriz 3x2 con los enteros del 1 al 6. Utiliza la función  de numpy apropiada  para obtener la descomposicion SVD reducida de la matriz $A=USV^t$.


In [1]:
import numpy as np

Para calcular la descomposición SVD reducida tenemos que utilizar la función `np.lingalg.svd()` con el parámetro `full_matrices=False`, ya que por defecto es `True` y las dimensiones no cuadrarían para hacer la reconstrucción. También hay que tener en cuenta que la función nos devuelve `s`, que corresponde a los valores singulares, y para obtener `S` tenemos que transformarlo en una matriz diagonal con `np.diag(s)`.

In [2]:
A = np.array([[1,2],
             [3,4],
             [5,6]])
U, s, Vt = np.linalg.svd(A, full_matrices=False)
S = np.diag(s)
A.shape, U.shape, S.shape, Vt.shape

((3, 2), (3, 2), (2, 2), (2, 2))

**Comprueba que $A=USV^t$**. 

Por problemas de precisión en los cálculos es conveniente comprobar que la diferencia es realmente pequeña $||A-USV^t||$. Deberias obtener una diferencia menor que $10^{-10}$ 

_Nota_:Utiliza la función adecuada de python para calcular la **norma** y  medir la distancia. Algo como **norm**? Investiga

Calculando la norma según `np.linalg.norm()` podemos ver que la diferencia entre las dos matrices, la original y la reconstruida, es verdaderamente pequeña. Ahora podemos estar tranquilos porque el cálculo parece estar realizándose correctamente.

> Nota: Para calcular el producto matricial se pueden utilizar tanto `np.matmult()`, `.dot()` y `@`, por lo que por simplicidad escribiremos `@`.

In [3]:
np.linalg.norm(A -(U @ S @ Vt))

2.4424906541753444e-15

La pseudoinversa se puede calcular como  $A^+=VS^{-1}U^t$. Comprueba que el resultado utilizando la función `pinv` de la librería `numpy` proporciona el mismo resultado.

In [4]:
Si = np.linalg.inv(S)
Api = Vt.T @ Si @ U.T
Api

array([[-1.33333333, -0.33333333,  0.66666667],
       [ 1.08333333,  0.33333333, -0.41666667]])

In [5]:
np.linalg.pinv(A)

array([[-1.33333333, -0.33333333,  0.66666667],
       [ 1.08333333,  0.33333333, -0.41666667]])

La función `np.allclose()` nos devuelve `True` o `False` si la diferencia entre dos matrices está por debajo de cierto threshold de confianza, `r_tol` y `a_tol`. Podemos utilizarla a lo largo de este ejercicio para comprobar si dos matrices son suficientemente parecidas.

In [6]:
np.allclose(Api, np.linalg.pinv(A))

True

# Condiciones de Penrose

La pseudoinversa $A^+$ cumple las siguientes propiedades:

1. $AA^+A=A$
2. $A^+AA^+=A^+$
3. $A^+A= (A^+A)^t$
4. $AA^+= (AA^+)^t$

**Comprueba que no se cumple $AA^+=I$**.

Es decir $A^+$ no es la matriz inversa $A^{-1}$.

_Nota: I es la matriz unidad._  


In [7]:
#A*A_plus!= Identidad
A_Api = A @ Api
## Con np.identity podemos obtener la matriz identidad de dimensión n.
## Le pedimos que nos la haga de la primera dimensión de la matriz A_Api para que 
## tengan las mismas dimensiones.
np.allclose(A_Api, np.identity(n=A_Api.shape[0]))

False

**Comprueba que se cumple $AA^+A=A$**. 

La primera condición de Penrose, hace que aparentemente $A^+$ realice la función de matriz inversa $A^{-1}$ porque transforma $A$ nuevamente en $A$ tal y como cumple la matriz inversa $AA^{-1}A=A$.

In [8]:
#Comprobamos que  A*A_plus*A es A, como la inversa!!!! Sin serlo!!!!
np.allclose(A @ Api @ A, A)

True

Esta "idea" es la que facilita resolver situaciones en las que no existe la matriz inversa. 

# Sistema de ecuaciones determinado.

En este tipo de ecuaciones $Ax=b$, cuando hay una solución única, esta se puede obtener como $x=A^{-1}b$. 

Dada la matriz A=[[3,-4],[2,4]] y B =[[-6],[16]] 

* Calcula $x$ empleando la función **solve** de numpy. 
* Calcula $x$ empleando la pseudoinversa como $x=A^{+}b$

In [9]:
A = np.array([[3,-4],
              [2,4]])
B = np.array([[-6],
              [16]])
A, B

(array([[ 3, -4],
        [ 2,  4]]),
 array([[-6],
        [16]]))

In [10]:
np.linalg.solve(A, B)

array([[2.],
       [3.]])

In [11]:
np.linalg.pinv(A) @ B

array([[2.],
       [3.]])

Comprueba también que la pseudoinversa $A^+$ coincide con la matriz inversa y, por tanto, también resuelve el sistema de ecuaciones.

In [12]:
np.allclose(np.linalg.pinv(A), np.linalg.inv(A))

True

# Sistema de ecuaciones indeterminado. 

En este tipo de ecuaciones $Ax=b$, donde NO hay una solución única, esta NO se puede obtener como $x=A^{1-}b$ porque no existe la matriz inversa. 

Dada la matriz A=[[1,3,5],[2,4,6]] y B =[[37],[48]], comprueba que el sistema de ecuaciones no tiene solución única porque el rango de la matriz $A$ es igual que el rango de la matriz ampliada $M$ pero menor que el número de variables del sistema de ecuaciones (Teorema de Rouché): 

_Nota_: el rango de una matriz se puede obtener con alguna instrucción de python, averigualo...

_Nota_: la matriz ampliada $M=[A|b]$ se obtiene añadiendo el témino independiente $b$ como una columna más de la matriz $A$

In [13]:
A = np.array([[1,3,5],
              [2,4,6]])
B = np.array([[37],
              [48]])
A, B

(array([[1, 3, 5],
        [2, 4, 6]]),
 array([[37],
        [48]]))

El rango de una matriz se puede obtener con la función `np.linalg.matrix_rank()`. Para obtener la matriz ampliada `A|B` podemos utilizar la función `np.concatenate()` y concatenar las matrices por la dimensión de las columnas.

Comprobamos que el rango de la matriz `A` es igual al rango de la matriz ampliada `A|B`, pero es menor que el número de las variables, que se puede obtener simplemente como la cantidad de columnas de la matriz `A`.

In [14]:
print(f"El rango de la matriz A es: {np.linalg.matrix_rank(A)}")
print(f"El rango de la matriz ampliada A|B es: {np.linalg.matrix_rank(np.concatenate([A,B], axis=1))}")
print(f"El número de variables del sistema de ecuaciones es: {A.shape[-1]}")

El rango de la matriz A es: 2
El rango de la matriz ampliada A|B es: 2
El número de variables del sistema de ecuaciones es: 3


Obtén una solución utilizando la pseudoinversa. Comprueba que es correcta. 

In [15]:
x = np.linalg.pinv(A) @ B
x

array([[2.66666667],
       [3.66666667],
       [4.66666667]])

Para comprobar que la solución de la ecuación es correcta podemos comprobar simplemente que se cumple la relación `Ax=B`.

In [16]:
B_calc = (A*x.squeeze()).sum(axis=1)
B_calc

array([37., 48.])

In [17]:
np.allclose(B.ravel(), B_calc.ravel())

True

# Sistema de ecuaciones incompatible.

En este tipo de ecuaciones $Ax=b$, donde NO hay una solución. Aún así podemos obtener una solución que minimice la distancia entre $Ax$ y $b$, es decir minimizar la norma $||Ax-b||$, utilizando la pseudoinversa $x=A^{+}b$. 

Dada la matriz A=[[1,1,1,1],[1,1,-1,-1],[2,0,1,1],[0,2,-1,-1]] y B =[[[1],[2],[0],[4]]. Comprueba que el sistema de ecuaciones no tiene solución porque el rango de la matriz $A$ menor que el rango de la matriz ampliada $M$ (Teorema de Rouché): 

_Nota_ : el rango de una matriz se puede obtener con alguna instrucción de python, averigualo...

_Nota_ : la matriz ampliada $M=[A|b]$ se obtiene añadiendo el témino independiente $b$ como una columna más de la matriz $A$

In [18]:
A = np.array([[1,1,1,1],
              [1,1,-1,-1],
              [2,0,1,1],
              [0,2,-1,-1]])
B = np.array([[1],
              [2],
              [0],
              [4]])
A, B

(array([[ 1,  1,  1,  1],
        [ 1,  1, -1, -1],
        [ 2,  0,  1,  1],
        [ 0,  2, -1, -1]]),
 array([[1],
        [2],
        [0],
        [4]]))

Ahora podemos ver que el rango de la matriz `A` es menor que el rango de la matriz ampliada `A|B`, por lo que el sistema es incompatible.

In [19]:
print(f"El rango de la matriz A es: {np.linalg.matrix_rank(A)}")
print(f"El rango de la matriz ampliada A|B es: {np.linalg.matrix_rank(np.concatenate([A,B], axis=-1))}")
print(f"El número de variables del sistema de ecuaciones es: {A.shape[-1]}")

El rango de la matriz A es: 3
El rango de la matriz ampliada A|B es: 4
El número de variables del sistema de ecuaciones es: 4


Calcula $x=A^{+}b$ y comprueba que no es solución del sistema de ecuaciones $Ax=b$.

In [20]:
x = np.linalg.pinv(A) @ B
x

array([[ 0.125],
       [ 1.625],
       [-0.25 ],
       [-0.25 ]])

Para comprobar que la solución de la ecuación es correcta podemos comprobar simplemente que se cumple la relación `Ax=B`.

In [21]:
B_calc = (A*x.squeeze()).sum(axis=1)
B_calc, B

(array([ 1.25,  2.25, -0.25,  3.75]),
 array([[1],
        [2],
        [0],
        [4]]))

In [22]:
np.allclose(B.ravel(), B_calc.ravel())

False